# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jpartane <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/19 15:51:03 by jpartane          #+#    #+#              #
#    Updated: 2019/10/21 10:33:40 by jpartane         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRC = srcs/*.c

all: $(NAME) clean

$(NAME):
	gcc $(SRC) -o $(NAME)
clean:
	rm -f *.o
fclean: clean
	rm -f $(NAME)

